# Generated by Django 5.2.13 on 2026-06-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_enhance_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
